name: "Hello World"
description: "Greet someone"
inputs:
  file:
    description: "File to upload"
    required: true

  s3-bucket:
    description: "S3 bucket"
    required: true

  s3-prefix:
    description: "The prefix in the bucket for where to place the files. Should contain version number"
    required: true

  set-as-latest:
    description: "Whether to set the uploaded files as latest in the bucket"
    required: false

  update-github-release:
    description: "Whether to update the latest release with the new version"
    required: false

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Set version number
      run: echo "VERSION=$(npm pkg get version --workspaces=false | tr -d '"')" >> $GITHUB_ENV
      shell: bash

    - name: Get hash of the file
      id: hash
      run: echo "HASH=$(openssl dgst -sha384 -binary ${{ inputs.file }} | openssl base64 -A)" >> $GITHUB_ENV
      shell: bash

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Upload to version path
      run: aws s3 cp ./dist/ s3://${{ inputs.s3-bucket }}/${{ inputs.s3-prefix }}/${{ env.version }}/ --recursive  --exclude "*" --include "*.tgz" --include "*.umd.min.js" --include "*.js.map" --acl public-read
      shell: bash

    - name: Upload to latest path
      if: ${{ inputs.set-as-latest == 'true'}}
      run: aws s3 cp ./dist/ s3://${{ inputs.s3-bucket }}/${{ inputs.s3-prefix }}/latest/ --recursive  --exclude "*" --include "*.tgz" --include "*.umd.min.js" --include "*.js.map" --acl public-read
      shell: bash

    - name: Update latest Github release with script import
      if: ${{ inputs.update-github-release == 'true'}}
      run: bash update_github_release.sh "**Use from CDN** <br /><br /><script src='https://assets.dintero.com/${{ inputs.s3-prefix }}/${{ env.version }}/dintero-checkout-web-sdk.umd.min.js' integrity="sha-384-${{ env.HASH }}" crossorigin="anonymous"></script>"
      shell: bash
