name: "Hello World"
description: "Greet someone"
inputs:
  file:
    description: "File to upload"
    required: true

  s3-bucket:
    description: "S3 bucket"
    required: true

  version-prefix:
    description: "The prefix in the bucket for where to place the files. Should contain version number"
    required: true

  latest-prefix:
    description: "The prefix in the bucket for where to place the files. Should contain latest"
    required: false

  version:
    description: "Version of the package"
    required: true

  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Set version number
      run: echo "VERSION=$(npm pkg get version --workspaces=false | tr -d '"')" >> $GITHUB_ENV
      shell: bash

    - name: Get hash of the file
      run: echo "HASH=$(openssl dgst -sha384 -binary ${{ inputs.file }} | openssl base64 -A)" >> $GITHUB_ENV
      shell: bash

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Deploy app build to S3 bucket for version
      run: aws s3 cp ./dist/ s3://${{ inputs.s3-bucket }}/${{ inputs.s3-prefix }}/ --recursive  --exclude "*" --include "*.tgz" --include "*.umd.min.js" --include "*.js.map" --acl public-read
      shell: bash
