name: CI

on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - name: yarn install, build, test and lint
        run: |
          yarn install --immutable
          yarn run test
          yarn run build
          yarn run lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ASSETS_DEPLOY_ROLE }}
          aws-region: eu-west-1

      - name: Upload to CDN
        uses: ./.github/actions/cdn
        with:
          file: "dintero-checkout-web-sdk.umd.min.js"
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-prefix: "pkg/checkout-web-sdk"
          set-as-latest: true
          update-github-release: true
