name: CI

on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe50206 # v7.0.0
        with:
          node-version: "lts/*"
          cache: pnpm
      - id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: '148.0.7778.167'
          install-dependencies: true
          install-chromedriver: true
      - run: make dependencies
      - run: make lint
      - env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
        run: make test
      - run: make build

      - name: Configure AWS credentials
        if: github.actor != 'dependabot[bot]'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ASSETS_DEPLOY_ROLE }}
          aws-region: eu-west-1

      - name: Upload to CDN
        if: github.actor != 'dependabot[bot]'
        uses: ./.github/actions/cdn
        with:
          file: "dintero-checkout-web-sdk.umd.min.js"
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-prefix: "pkg/checkout-web-sdk"
          set-as-latest: false
          update-github-release: false
