name: CI

on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - name: yarn install, build, test and lint
        run: |
          yarn install --immutable
          yarn run test
          yarn run build
          yarn run lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ASSETS_DEPLOY_ROLE }}
          aws-region: eu-west-1

      - name: Set version number
        run: echo "VERSION=$(npm pkg get version --workspaces=false | tr -d '"')" >> $GITHUB_ENV

      - name: Get hash of the dintero-checkout-web-sdk.umd.min.js
        run: echo "HASH=$(openssl dgst -sha384 -binary dist/dintero-checkout-web-sdk.umd.min.js | openssl base64 -A)" >> $GITHUB_ENV

      - name: Deploy app build to S3 bucket for version
        run: aws s3 cp ./dist/ s3://${{ secrets.S3_BUCKET }}/pkg/checkout-web-sdk/${VERSION}/ --recursive  --exclude "*" --include "*.tgz" --include "*.umd.min.js" --include "*.js.map" --acl public-read

      - name: Deploy app build to S3 bucket for latest
        run: aws s3 cp ./dist/ s3://${{ secrets.S3_BUCKET }}/pkg/checkout-web-sdk/latest/ --recursive  --exclude "*" --include "*.tgz" --include "*.umd.min.js" --include "*.js.map" --acl public-read
