name: CI

on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - name: yarn install, build, test and lint
        run: |
          yarn install --immutable
          yarn run test
          yarn run build
          yarn run lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ASSETS_DEPLOY_ROLE }}
          aws-region: eu-west-1

      - name: Set version number
        run: echo "VERSION=${npm pkg get version --workspaces=false}" >> $GITHUB_ENV

      - name: Deploy app build to S3 bucket
        run: aws s3 cp ./dist/ s3://assets.dintero.com/pkg/checkout-web-sdk/$VERSION/ --recursive  --exclude "*" --include "*.tgz" --include "*.js" --include "*.js.map" --acl public-read
