name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
          - 17

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: npm install, build and test
      run: |
        npm install
        npm run test
        npm run build
