name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      packages: write
      issues: write
      pull-requests: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies, test and lint
        run: |
          yarn install --immutable
          yarn run test
          yarn run lint
          yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: yarn run semantic-release

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ASSETS_DEPLOY_ROLE }}
          aws-region: eu-west-1

      - name: Upload to CDN
        uses: ./.github/actions/cdn
        with:
          file: "dintero-checkout-web-sdk.umd.min.js"
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-prefix: "pkg/checkout-web-sdk"
          set-as-latest: true
          update-github-release: true
